'use strict';

const lang  = {
    lCurrent: 'Ua',

    //models/helper
    lHelpOffline: 'offline',
    lHelpYear: 'рік',
    lHelpYear14: 'роки',
    lHelpYearMany: 'років',
    lHelpMonth: 'місяць',
    lHelpMonth14: 'місяці',
    lHelpMonthMany: 'місяців',
    lHelpDay: 'день',
    lHelpDay14: 'дні',
    lHelpDayMany: 'днів',
    lHelpHour: 'година',
    lHelpHour14: 'години',
    lHelpHourMany: 'годин',
    lHelpMinute: 'хвилина',
    lHelpMinute14: 'хвилини',
    lHelpMinuteMany: 'хвилин',
    lHelpOnline: 'online',
    lHelpAgo: ' тому',
	lHelpMonths: ['січня', 'лютого', 'березня', 'квітня', 'травня', 'червня', 'липня', 'серпня', 'вересня', 'жовтня', 'листопада', 'грудня'],

    //models/gift
    lGiftTextPart1: 'Користувач',
    lGiftTextPart2: 'надіслав(-ла) вам подарунок!',

    //bot-chat-id, dating-users
    lLoadMore: 'Завантажити ще',
    lSendBoxPlaceholder: ' Напишіть повідомлення...',

    //dating
    lRatingTitle: 'Рейтинг ',
    lNextUser: 'Пропустити',
    lMenuProfile: 'Профіль',
    lMenuFavorite: 'Підписка',
    lMenuMessage: 'Повідомлення',
    lInfoRibbon: 'Моя романтична історія почнеться тут!',
    lISearch: 'Я шукаю:',
    lSearchAge: 'Вік:',
    lCheckGender: 'Стать:',
    lCheckMale: 'чоловіча',
    lCheckFemale: 'жіноча',
    lCheckCity: 'Місто',
    lCheckCityChoose: '--- Обрати ---',
    lCheckOnlyOnline: 'Тільки online',
    lSearchBtn: 'Пошук',
    lEnterBtn: 'Вхід',
    lRegisterBtn: 'Реєстрація',
    lGiftsHeaderGifts: 'Подарунки',
    lGiftsHeaderMake: 'Подарувати',
    lGiftsConfirmPrice: 'Х монет',
    lGiftsConfirmTitle: 'Подарувати?',
    lGiftsConfirmBuyBtn: 'купити',
    lGiftsConfirmCancelBtn: 'скасувати',

    //fans, favorites
    lOnlineStatus: 'online',
    lAgeTitle: 'Вік:',
    lAgeYears: 'років,',
    lProfileCountry: 'Україна',
    lMenuChat: 'Повідомлення',

    //footer
    lPublicNotifyMessage: 'Ти зможеш відправляти особисті повідомлення як тільки зробиш свій ' +
    'профіль доступним в знайомствах для інших учасників',
    lPublicNotifySettingsBtn: 'Налаштування',
    lPublicNotifyCancelBtn: 'Скасувати',

    //sidemenu
    lSidemenuName: "І'мя",
    lSidemenuAge: 'Вік',
    lSidemenuCity: 'Місто',
    lSidemenuEnter: 'Увійти',
    lSidemenuNews: 'Новини',
    lSidemenuMessages: 'Повідомлення',
    lSidemenuMeetings: 'Знайомства',
    lSidemenuFavorites: 'Фаворити',
    lSidemenuFans: 'Шанувальники',
    lSidemenuPeople: 'Підписки',
    lSidemenuRibbon: 'Стрічка',
    lSidemenuMusic: 'Музика',
    lSidemenuRadio: 'Радіо',
    lSidemenuNotifications: 'Сповіщення',
    lSidemenuSettings: 'Налаштування',

    //header
    lHeaderTitle: 'Головна',
    lHeadingAge: 'років',
    lHeadingOnline: 'online',
    lHeadingOffline: 'offline',
    lHeadingTitleFavorites: 'Фаворити',
    lHeadingTitleFans: 'Шанувальники',
    lHeadingTitleSettings: 'Налаштування',
    lHeadingTitleNews: 'Новини',
    lHeadingTitleMessages: 'Повідомлення',
    lHeadingTitleRadio: 'Радіо',
    lHeadingTitleMySub: 'Вподобані',
    lHeadingTitleSubToMe: 'Прихильники',

    //header-admin
    lSidemenuMessagesRibbon: 'Стрічка повідомлень',
    lSidemenuUsers: 'Користувачі',
    lSidemenuBotChat: 'Ботчат',

    //register-login forms
    lFormNickPlace: 'Нік...',
    lFormMailPlace: 'Пошта...',
    lFormPassPlace: 'Пароль...',
    lFormPassConfPlace: 'Повтор пароля...',
    lFormRegisterBtn: 'Зареєструватися',
    lFormLoginBtn: 'Увійти',
    lFormLoginSoc: 'увійти',

    //messages
    sendBoxPlaceholder: ' Напишіть повідомлення...',

    //news
    lNewsFilterHour: 'Година',
    lNewsFilterToday: 'Сьогодні',
    lNewsFilterYesterday: 'Вчора',
    lNewsFilterWeek: 'Тиждень',

    //notifications
    lNotifTitle: 'Сповіщення',
    lNotifClearBtn: 'Відмітити як прочитані',
    lNotifTextStart: 'Користувач',
    lNotifTextEnd: 'запитує Ваші контактні дані.',
    lNotifRequestAccept: 'Прийняти',
    lNotifRequestDecline: 'Відхилити',
    lNotifDeclineTitle: 'Виберіть причину відхилення',
    lNotifDeclineReason1: 'Погане знання англійської',
    lNotifDeclineReason2: 'Неготовий(а) поділитись персональними даними',
    lNotifDeclineReason3: 'Недостатній термін знайомства',

    //profile, profile-id
    lProfileEditBtn: 'Редагувати профіль',
    lProfileDropdownInfo: 'інформація',
    lProfileInfoResidence: 'Місто',
    lProfileInfoBdate: 'Дата народження',
    lProfileInfoGender: 'Стать',
    lProfileInfoEues: 'Колір очей',
    lProfileInfoHair: 'Колір волосся',
    lProfileInfoBodyType: 'Фігура',
    lProfileInfoWeight: 'Вага',
    lProfileInfoKG: 'кг',
    lProfileInfoHeight: 'Зріст',
    lProfileInfoSM: 'см',
    lProfileInfoReligion: 'Релігія',
    lProfileInfoEducation: 'Освіта',
    lProfileInfoOccupation: 'Професія',
    lProfileInfoSmoke: 'Куріння',
    lProfileInfoDrink: 'Алкоголь',
    lProfileInfoHobbies: 'Хоббі',
    lProfileInfoColors: 'Улюблені кольори',
    lProfileInfoSport: 'Спорт',
    lProfileInfoAbroad: 'Бував(ла) закордоном',
    lProfileInfoInterests: 'Інтереси',
    lProfileInfoCharacter: 'Характер',
    lProfileInfoMarital: 'Сімейний стан',
    lProfileInfoChildren: 'Діти',
    lProfileInfoGoal: 'Ціль знайомства',
    lProfileDropdownAboutMyself: 'Про себе',
    lProfileDropdownAboutPartner: 'я шукаю',
    lProfileDropdownPhoto: 'Фото',
    lProfileDropdownFeed: 'Стрічка',
    lProfilePhotoMain: 'Зробити головною',
    lProfilePhotoDeleteBtn: 'Видалити',
    lProfilePhotoAddBtn: 'Додати фото',
    lProfilePhotoLike: 'Подобається',
    lProfileVideoTitle: 'Як заповнити свій профіль (відеоінструкція)',
    lProfileBlockUserOption: 'Заблокувати',
    lProfileUnBlockUserOption: 'Розблокувати',
    lProfileClaimUser: 'Поскаржитись',
    lProfileClaimOptionsTitle: 'Що ви хочете зробити?',
    lProfileClaimOptionsPublications: 'Поскаржитись на публікації',
    lProfileClaimOptionsProfile: 'Поскаржитись на профіль',
    lProfileClaimSend: 'Надіслати',

    //profile-edit
    lInfoEditTitle: 'Інформація',
    lInfoEditProfileLink: 'До профілю',
    lInfoEditStatus: 'Статус',
    lInfoEditPlaceNotFilled: 'не заповнено...',
    lInfoEditSaveBtn: 'зберегти',
    lInfoEditCancelBtn: 'скасувати',
    lInfoEditName: "Ім'я",
    lInfoEditSurname: 'Прізвище',
    lInfoEditNickname: 'Нікнейм',
    lInfoEditUseNickname: 'Використовувати нік замість імені',
    lInfoEditOptionYes: 'Так',
    lInfoEditOptionNo: 'Ні',
    lMonthJanuary: 'січня',
    lMonthFebruary: 'лютого',
    lMonthMarch: 'березня',
    lMonthApril: 'квітня',
    lMonthMay: 'травня',
    lMonthJune: 'червня',
    lMonthJuly: 'липня',
    lMonthAugust: 'серпня',
    lMonthSeptember: 'вересня',
    lMonthOctober: 'жовтня',
    lMonthNovember: 'листопада',
    lMonthDecember: 'грудня',

    //radio
    lRadioArtist: 'Виконавець',
    lRadioTrackName: 'Назва пісні',
    lRadioNameCopied: 'Назву пісні скопійовано',

    //settings, settings-guest
    lSetTitleLang: 'Мова',
    lSetLangUa: 'Українська мова',
    lSetLangRu: 'Російська мова',
    lSetTitlePrivacy: 'Приватність',
    lSetPubProfile: 'Публічний профіль',
    lSetShowComments: 'Показувати мої коментарі до новин',
    lSetTitleDating: 'Знайомства',
    lSetWannaDateCond: '1. Відмітити пункт "Знайомлюсь в налаштуваннях"',
    lSetWannaDateCheck: '   Знайомлюсь!',
    lSetChoosePhotoCond: '2. Оберіть фотографію профілю',
    lSetBdateCond: '3. Вкажіть дату народження',
    lSetCityCond: '4. Вкажіть місто в якому живете',
    lSetGenderCond: '5. Вкажіть стать',
    lSetSummaryCond: '6. Коли всі умови будуть виконані, Ваша анкета стане ' +
    'доступною для інших користувачів.',
    lSetExitProfile: 'Вийти з профілю',
    lSetDateVideoTitle: 'Як налаштувати відображення в знайомствах (відеоінструкція):',
    lSetAllowText: "Вітаємо! Ви відображаєтесь в знайомствах! ",
    lSetNotAllowText: "Ви не відображаєтесь в знайомствах!",

    //transactions
    lTransSN: 'С/Н',
    lTransSpentOn: 'На',
    lTransPayType: 'Тип',
    lTransSpentPay: 'К-ть',
    lTransDate: 'Дата',

    //subscribe
    lSubISus: 'Відстежуються',
    lSubToMeSub: 'Стежать',
    lSubActSub: 'Стежити',
    lSubActNotSub: 'Відстежується',

    //music
    lMusicVideoTitle: 'Як користуватися музичним сховищем (відеоінструкція):'
};

module.exports = lang;