module.exports = {
  OK: 'OK',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_INPUT_PARAMETERS: 'INVALID_INPUT_PARAMETERS',
  INVALID_PARAMETERS: 'INVALID_PARAMETERS',
  ACCESS_DENIED: 'ACCESS_DENIED',
  NOT_FOUND: 'NOT_FOUND'
};